# Generated by Django 4.0.4 on 2022-05-20 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=300)),
                ('original_url', models.URLField(max_length=300)),
                ('brand_name', models.CharField(max_length=255)),
                ('image_type', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=300)),
                ('scrapped_at', models.DateTimeField(auto_now_add=True)),
                ('original_height', models.IntegerField()),
                ('original_width', models.IntegerField()),
                ('format', models.CharField(max_length=100)),
                ('is_animated', models.BooleanField()),
                ('mode', models.CharField(blank=True, max_length=100, null=True)),
                ('brightness', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('focal_length', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_of', to='catalog.image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
