# Generated by Django 4.0.4 on 2022-05-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemetadata',
            name='focal_length',
        ),
        migrations.AlterField(
            model_name='imagemetadata',
            name='scrapped_at',
            field=models.DateTimeField(),
        ),
    ]
