# Generated by Django 4.0.4 on 2022-05-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_imagemetadata_focal_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='directory',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
